### ISSUE TITLE
Searching for a valid package name, that includes slashes, will fail.

### ISSUE THREAD

**Issue by itsluketwist** [andylamp/quibraries#1]
**For example:** `github.com/pkg/term` is a valid package in libraries.io: https://libraries.io/go/github.com%2Fpkg%2Fterm

But the following code will send a GET request to `https://libraries.io/api/go/github.com/pkg/term?api_key=<token>&page=1&per_page=30`, which is an invalid endpoint, resulting in a 404 error.

```
from quibraries import Search
search = Search("<gituhb_token>")
result = search.project("go", "github.com/pkg/term")
```

Instead, a GET request should be sent to `https://libraries.io/api/go/github.com%2Fpkg%2Fterm?api_key=<key>&page=1&per_page=30` - encoding the `/` in the package name before creating the url.

**More generally:** strings need to be encoded before building the URL for the request.

**Suggested fix:** encode the args before adding them to `url_end_list`, in `SearchAPI._uri_handler(...)`.

**Comment by andylamp** [comment]
@itsluketwist thanks for the catch! And appreciate the fix 👌.
